import Image from "next/image";

export const metadata = {
  title: "VicoNet - Login",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div className="h-screen grid grid-cols-2 gap-0">
      <div className="bg-[url('/bg.jpg')] bg-cover bg-center">
        <div className="flex h-screen flex-col justify-center text-center px-14 items-center">
          <Image src="/logowhite.svg" width={190} height={190} alt="Logo" />
          <p className="text-white font-bold text-3xl mt-10">
            Get connected and access possible career or business opportunities.
          </p>
        </div>
      </div>
      <div className="bg-gray-100">
        <div className="flex justify-center pt-50">{children}</div>
      </div>
    </div>
  );
}
