export const skills = [
    { "value": "c1", "label": "C#" },
    { "value": "c2", "label": "C++" },
    { "value": "c3", "label": "Java" },
    { "value": "c4", "label": "JavaScript" },
    { "value": "c5", "label": "Python" },
    { "value": "c6", "label": "SQL" },
    { "value": "c7", "label": "React.js" },
    { "value": "c8", "label": "Angular" },
    { "value": "c9", "label": "SAP" },
    { "value": "c10", "label": "Salesforce" },
    { "value": "c11", "label": "Vue.js" },
    { "value": "c12", "label": "Angular.js" },
    { "value": "c13", "label": "Git" },
    { "value": "c14", "label": "DevOps" },
    { "value": "c15", "label": "Azure" },
    { "value": "c16", "label": "AWS" },
    { "value": "c17", "label": "HTML" },
    { "value": "c18", "label": "CSS" },
    { "value": "c19", "label": "PHP" },
    { "value": "c20", "label": "Ruby" },
    { "value": "c21", "label": "Swift" },
    { "value": "c22", "label": "Objective-C" },
    { "value": "c23", "label": "Kotlin" },
    { "value": "c24", "label": "R" },
    { "value": "c25", "label": "Perl" },
    { "value": "c26", "label": "Shell scripting" },
    { "value": "c27", "label": "Go" },
    { "value": "c28", "label": "TypeScript" },
    { "value": "c29", "label": "Scala" },
    { "value": "c30", "label": "Haskell" },
    { "value": "c31", "label": "Lua" },
    { "value": "c32", "label": "MATLAB" },
    { "value": "c33", "label": "PowerShell" },
    { "value": "c34", "label": "MongoDB" },
    { "value": "c35", "label": "Docker" },
    { "value": "c36", "label": "Kubernetes" },
    { "value": "c37", "label": "Jenkins" },
    { "value": "c38", "label": "Ansible" },
    { "value": "c39", "label": "Terraform" },
    { "value": "c40", "label": "Project management" },
    { "value": "c41", "label": "Agile methodology" },
    { "value": "c42", "label": "Scrum" },
    { "value": "c43", "label": "Waterfall methodology" },
    { "value": "c44", "label": "Lean Six Sigma" },
    { "value": "c45", "label": "Business analysis" },
    { "value": "c46", "label": "Risk management" },
    { "value": "c47", "label": "Change management" },
    { "value": "c48", "label": "Stakeholder management" },
    { "value": "c49", "label": "Quality assurance" },
    { "value": "c50", "label": "Software testing" },
    { "value": "c51", "label": "Test planning" },
    { "value": "c52", "label": "Test case design" },
    { "value": "c53", "label": "Test execution" },
    { "value": "c54", "label": "Defect tracking" },
    { "value": "c55", "label": "Test automation" },
    { "value": "c56", "label": "Performance testing" },
    { "value": "c57", "label": "Load testing" },
    { "value": "c58", "label": "Security testing" },
    { "value": "c59", "label": "Usability testing" },
    { "value": "c60", "label": "Mobile app testing" },
    { "value": "c61", "label": "Web application testing" },
    { "value": "c62", "label": "Database testing" },
    { "value": "c63", "label": "API testing" },
    { "value": "c64", "label": "Regression testing" },
    { "value": "c65", "label": "Integration testing" },
    { "value": "c66", "label": "System testing" },
    { "value": "c67", "label": "Acceptance testing" },
    { "value": "c68", "label": "Exploratory testing" },
    { "value": "c69", "label": "Test management" },
    { "value": "c70", "label": "Test documentation" },
    { "value": "c71", "label": "Test reporting" },
    { "value": "c72", "label": "Code review" },
    { "value": "c73", "label": "Code refactoring" },
    { "value": "c74", "label": "Code versioning" },
    { "value": "c75", "label": "Debugging" },
    { "value": "c76", "label": "Software architecture" },
    { "value": "c77", "label": "RESTful API" },
    { "value": "c78", "label": "Microservices" },
    { "value": "c79", "label": "Object-oriented programming" },
    { "value": "c80", "label": "Functional programming" },
    { "value": "c81", "label": "Data structures" },
    { "value": "c82", "label": "Algorithms" },
    { "value": "c83", "label": "Artificial intelligence" },
    { "value": "c84", "label": "Machine learning" },
    { "value": "c85", "label": "Deep learning" },
    { "value": "c86", "label": "Natural language processing" },
    { "value": "c87", "label": "Computer vision" },
    { "value": "c88", "label": "Big data" },
    { "value": "c89", "label": "Data mining" },
    { "value": "c90", "label": "Data visualization" },
    { "value": "c91", "label": "Data warehousing" },
    { "value": "c92", "label": "Business intelligence" },
    { "value": "c93", "label": "Cybersecurity" },
    { "value": "c94", "label": "Network security" },
    { "value": "c95", "label": "Web security" },
    { "value": "c96", "label": "Cloud security" },
    { "value": "c97", "label": "Ethical hacking" },
    { "value": "c98", "label": "Vulnerability assessment" },
    { "value": "c99", "label": "Incident response" },
    { "value": "c100", "label": "Disaster recovery" },
    { "value": "c101", "label": "Business continuity planning" },
    { "value": "c102", "label": "ITIL" },
    { "value": "c103", "label": "Service management" },
    { "value": "c104", "label": "Change management" },
    { "value": "c105", "label": "Problem management" },
    { "value": "c106", "label": "IT asset management" },
    { "value": "c107", "label": "Service level management" },
    { "value": "c108", "label": "Configuration management" },
    { "value": "c109", "label": "Release management" },
    { "value": "c110", "label": "Agile project management" },
    { "value": "c111", "label": "Scrum" },
    { "value": "c112", "label": "Kanban" },
    { "value": "c113", "label": "Lean" },
    { "value": "c114", "label": "Six Sigma" },
    { "value": "c115", "label": "Risk management" },
    { "value": "c116", "label": "Change management" },
    { "value": "c117", "label": "Stakeholder management" },
    { "value": "c118", "label": "Quality management" },
    { "value": "c119", "label": "Agile testing" },
    { "value": "c120", "label": "Test-driven development (TDD)" },
    { "value": "c121", "label": "Behavior-driven development (BDD)" },
    { "value": "c122", "label": "Continuous integration (CI)" },
    { "value": "c123", "label": "Continuous delivery (CD)" },
    { "value": "c124", "label": "Continuous deployment (CD)" },
    { "value": "c125", "label": "Infrastructure as code (IaC)" },
    { "value": "c126", "label": "Serverless architecture" },
    { "value": "c127", "label": "Containerization" },
    { "value": "c128", "label": "Microservices architecture" },
    { "value": "c129", "label": "Event-driven architecture" },
    { "value": "c130", "label": "Domain-driven design (DDD)" },
    { "value": "c131", "label": "Test automation" },
    { "value": "c132", "label": "Performance testing" },
    { "value": "c133", "label": "Load testing" },
    { "value": "c134", "label": "Security testing" },
    { "value": "c135", "label": "Usability testing" },
    { "value": "c136", "label": "Accessibility testing" },
    { "value": "c137", "label": "Localization testing" },
    { "value": "c138", "label": "Internationalization testing" },
    { "value": "c139", "label": "Test management" },
    { "value": "c140", "label": "Defect tracking" },
    { "value": "c141", "label": "Test reporting" },
    { "value": "c142", "label": "Code review" },
    { "value": "c143", "label": "Code refactoring" },
    { "value": "c144", "label": "Code versioning" },
    { "value": "c145", "label": "Debugging" },
    { "value": "c146", "label": "Software architecture" },
    { "value": "c147", "label": "RESTful API" },
    { "value": "c148", "label": "Microservices" },
    { "value": "c149", "label": "Object-oriented programming" },
    { "value": "c150", "label": "Functional programming" }
]

export const courses =[
    { "value": "c0", "label": "Degree: Bachelor of Science in Computer Science" },
    { "value": "c1", "label": "Degree: Bachelor of Engineering in Software Engineering" },
    { "value": "c2", "label": "Degree: Bachelor of Technology in Information Technology" },
    { "value": "c3", "label": "Degree: Bachelor of Science in Information Systems" },
    { "value": "c4", "label": "Degree: Bachelor of Business Administration in Project Management" },
    { "value": "c5", "label": "Degree: Bachelor of Science in Computer Engineering" },
    { "value": "c6", "label": "Degree: Bachelor of Arts in Web Design and Development" },
    { "value": "c7", "label": "Degree: Bachelor of Science in Data Science" },
    { "value": "c8", "label": "Degree: Bachelor of Science in Cybersecurity" },
    { "value": "c9", "label": "Degree: Bachelor of Science in Network Administration" },
    { "value": "c10", "label": "Postgraduate Degree: Master of Science in Software Engineering" },
    { "value": "c11", "label": "Postgraduate Degree: Master of Science in Information Systems" },
    { "value": "c12", "label": "Postgraduate Degree: Master of Business Administration in Project Management" },
    { "value": "c13", "label": "Postgraduate Degree: Master of Science in Data Analytics" },
    { "value": "c14", "label": "Postgraduate Degree: Master of Science in Cybersecurity" },
    { "value": "c15", "label": "Postgraduate Degree: Master of Technology in IT Management" },
    { "value": "c16", "label": "Postgraduate Degree: Master of Science in Network Security" },
    { "value": "c17", "label": "Diploma: Diploma in Software Development" },
    { "value": "c18", "label": "Diploma: Diploma in Web Design" },
    { "value": "c19", "label": "Diploma: Diploma in Database Administration" },
    { "value": "c20", "label": "Diploma: Diploma in IT Support" },
    { "value": "c21", "label": "SAP Certification: SAP Certified Application Associate - Financial Accounting" },
    { "value": "c22", "label": "SAP Certification: SAP Certified Development Associate - ABAP with SAP NetWeaver" },
    { "value": "c23", "label": "SAP Certification: SAP Certified Technology Associate - System Administration" },
    { "value": "c24", "label": "SAP Certification: SAP Certified Application Associate - Sales and Distribution" },
    { "value": "c25", "label": "SAP Certification: SAP Certified Development Associate - SAP HANA" },
    { "value": "c26", "label": "SAP Certification: SAP Certified Technology Associate - Database Administrator" },
    { "value": "c27", "label": "SAP Certification: SAP Certified Application Associate - Human Capital Management" },
    { "value": "c28", "label": "SAP Certification: SAP Certified Development Associate - Fiori Application Developer" },
    { "value": "c29", "label": "SAP Certification: SAP Certified Technology Associate - Security Consultant" },
    { "value": "c30", "label": "SAP Certification: SAP Certified Application Associate - Procurement" },
    { "value": "c31", "label": "SAP Certification: SAP Certified Development Associate - Cloud Integration" },
    { "value": "c32", "label": "SAP Certification: SAP Certified Technology Associate - System Administrator (Oracle DB)" },
    { "value": "c33", "label": "SAP Certification: SAP Certified Application Associate - Project Manager" },
    { "value": "c34", "label": "SAP Certification: SAP Certified Development Associate - SAPUI5" },
    { "value": "c35", "label": "SAP Certification: SAP Certified Technology Associate - Solution Manager" },
    { "value": "c36", "label": "SAP Certification: SAP Certified Application Associate - Quality Management" },
    { "value": "c37", "label": "SAP Certification: SAP Certified Development Associate - ABAP for SAP HANA" },
    { "value": "c38", "label": "SAP Certification: SAP Certified Technology Associate - Database Administrator (MaxDB)" },
    { "value": "c39", "label": "SAP Certification: SAP Certified Application Associate - Plant Maintenance" },
    { "value": "c40", "label": "SAP Certification: SAP Certified Development Associate - SAP Mobile Platform" },
    { "value": "c41", "label": "SAP Certification: SAP Certified Technology Associate - System Administrator (MS SQL Server)" },
    { "value": "c42", "label": "SAP Certification: SAP Certified Application Associate - Production Planning" },
    { "value": "c43", "label": "SAP Certification: SAP Certified Development Associate - SAP Cloud Platform" },
    { "value": "c44", "label": "SAP Certification: SAP Certified Technology Associate - System Administrator (DB2)" },
    { "value": "c45", "label": "SAP Certification: SAP Certified Application Associate - Customer Service" },
    { "value": "c46", "label": "SAP Certification: SAP Certified Development Associate - Process Integration with SAP NetWeaver" },
    { "value": "c47", "label": "SAP Certification: SAP Certified Technology Associate - System Administrator (Sybase ASE)" },
    { "value": "c48", "label": "SAP Certification: SAP Certified Application Associate - Warehouse Management" },
    { "value": "c49", "label": "SAP Certification: SAP Certified Development Associate - SAP Cloud for Customer" },
    { "value": "c50", "label": "Degree: Master of Science in Information Systems" },
    { "value": "c51", "label": "Degree: Master of Science in Computer Science" },
    { "value": "c52", "label": "Degree: Master of Science in Software Engineering" },
    { "value": "c53", "label": "Degree: Master of Science in Data Science" },
    { "value": "c54", "label": "Degree: Master of Science in Cybersecurity" },
    { "value": "c55", "label": "Degree: Master of Business Administration in Project Management" },
    { "value": "c56", "label": "Degree: Master of Technology in IT Management" },
    { "value": "c57", "label": "Degree: Master of Science in Network Security" },
    { "value": "c58", "label": "Degree: Master of Science in Web Development" },
    { "value": "c59", "label": "Degree: Master of Science in Artificial Intelligence" },
    { "value": "c60", "label": "Degree: Master of Science in Cloud Computing" },
    { "value": "c61", "label": "Degree: Bachelor of Science in Software Testing" },
    { "value": "c62", "label": "Degree: Bachelor of Science in Quality Assurance" },
    { "value": "c63", "label": "Degree: Bachelor of Engineering in Test Automation" },
    { "value": "c64", "label": "Degree: Bachelor of Technology in Software Quality Management" },
    { "value": "c65", "label": "Degree: Bachelor of Science in Project Management" },
    { "value": "c66", "label": "Degree: Bachelor of Science in Agile Methodologies" },
    { "value": "c67", "label": "Degree: Bachelor of Arts in User Acceptance Testing" },
    { "value": "c68", "label": "Degree: Bachelor of Science in Test Planning and Execution" },
    { "value": "c69", "label": "Degree: Bachelor of Business Administration in Software Quality Assurance" },
    { "value": "c70", "label": "Degree: Bachelor of Science in Scrum Master" },
    { "value": "c71", "label": "Degree: Bachelor of Science in Project Quality Control" },
    { "value": "c72", "label": "Degree: Bachelor of Engineering in Performance Testing" },
    { "value": "c73", "label": "Degree: Bachelor of Technology in Test Environment Management" },
    { "value": "c74", "label": "Degree: Bachelor of Science in Risk-Based Testing" },
    { "value": "c75", "label": "Degree: Bachelor of Science in DevOps Testing" },
    { "value": "c76", "label": "Degree: Bachelor of Arts in Security Testing" },
    { "value": "c77", "label": "Degree: Bachelor of Science in Test Automation Frameworks" },
    { "value": "c78", "label": "Degree: Bachelor of Science in Load Testing" },
    { "value": "c79", "label": "Degree: Bachelor of Business Administration in Test Management" },
    { "value": "c80", "label": "Degree: Bachelor of Science in API Testing" },
    { "value": "c81", "label": "Degree: Bachelor of Science in Project Risk Management" },
    { "value": "c82", "label": "Degree: Bachelor of Arts in Agile Project Management" },
    { "value": "c83", "label": "Degree: Bachelor of Science in Quality Control" },
    { "value": "c84", "label": "Degree: Bachelor of Engineering in Configuration Management" },
    { "value": "c85", "label": "Degree: Bachelor of Technology in Defect Management" },
    { "value": "c86", "label": "Degree: Bachelor of Science in Test Reporting and Metrics" },
    { "value": "c87", "label": "Degree: Bachelor of Science in Test Case Design" },
    { "value": "c88", "label": "Degree: Bachelor of Business Administration in Continuous Integration" },
    { "value": "c89", "label": "Degree: Bachelor of Science in Exploratory Testing" },
    { "value": "c90", "label": "Degree: Bachelor of Science in Usability Testing" },
    { "value": "c91", "label": "Degree: Bachelor of Engineering in Test Data Management" },
    { "value": "c92", "label": "Degree: Bachelor of Technology in Security Testing" },
    { "value": "c93", "label": "Degree: Bachelor of Science in Mobile App Testing" },
    { "value": "c94", "label": "Degree: Bachelor of Science in Performance Engineering" },
    { "value": "c95", "label": "Degree: Bachelor of Arts in User Interface Testing" },
    { "value": "c96", "label": "Degree: Bachelor of Science in Test Strategy" },
    { "value": "c97", "label": "Degree: Bachelor of Science in Test Execution" },
    { "value": "c98", "label": "Degree: Bachelor of Business Administration in Quality Assurance" },
    { "value": "c99", "label": "Degree: Bachelor of Science in Project Documentation" },
    { "value": "c100", "label": "Certification: AWS Certified Solutions Architect - Associate" },
    { "value": "c101", "label": "Certification: AWS Certified Developer - Associate" },
    { "value": "c102", "label": "Certification: AWS Certified SysOps Administrator - Associate" },
    { "value": "c103", "label": "Certification: AWS Certified DevOps Engineer - Professional" },
    { "value": "c104", "label": "Certification: AWS Certified Solutions Architect - Professional" },
    { "value": "c105", "label": "Certification: AWS Certified Advanced Networking - Specialty" },
    { "value": "c106", "label": "Certification: AWS Certified Security - Specialty" },
    { "value": "c107", "label": "Certification: AWS Certified Machine Learning - Specialty" },
    { "value": "c108", "label": "Certification: AWS Certified Database - Specialty" },
    { "value": "c109", "label": "Certification: Microsoft Certified: Azure Administrator Associate" },
    { "value": "c110", "label": "Certification: Microsoft Certified: Azure Developer Associate" },
    { "value": "c111", "label": "Certification: Microsoft Certified: Azure Security Engineer Associate" },
    { "value": "c112", "label": "Certification: Microsoft Certified: Azure AI Engineer Associate" },
    { "value": "c113", "label": "Certification: Microsoft Certified: Azure Data Engineer Associate" },
    { "value": "c114", "label": "Certification: Microsoft Certified: Azure DevOps Engineer Expert" },
    { "value": "c115", "label": "Certification: Microsoft Certified: Azure Solutions Architect Expert" },
    { "value": "c116", "label": "Certification: Microsoft Certified: Azure AI Fundamentals" },
    { "value": "c117", "label": "Certification: Microsoft Certified: Azure Data Fundamentals" },
    { "value": "c118", "label": "Certification: Microsoft Certified: Azure Security Engineer" },
    { "value": "c119", "label": "Certification: Microsoft Certified: Azure Data Scientist" },
    { "value": "c120", "label": "Certification: Project Management Professional (PMP)" },
    { "value": "c121", "label": "Certification: Certified ScrumMaster (CSM)" },
    { "value": "c122", "label": "Certification: PRINCE2 Practitioner" },
    { "value": "c123", "label": "Certification: Agile Certified Practitioner (PMI-ACP)" },
    { "value": "c124", "label": "Certification: Certified Associate in Project Management (CAPM)" },
    { "value": "c125", "label": "Certification: Certified Project Management Professional (CPMP)" },
    { "value": "c126", "label": "Certification: Certified Scrum Product Owner (CSPO)" },
    { "value": "c127", "label": "Certification: ITIL Foundation Certification" },
    { "value": "c128", "label": "Certification: Certified Information Systems Security Professional (CISSP)" },
    { "value": "c129", "label": "Certification: Certified Ethical Hacker (CEH)" },
    { "value": "c130", "label": "Certification: CompTIA Security+" },
    { "value": "c131", "label": "Certification: Certified Information Privacy Professional (CIPP)" },
    { "value": "c132", "label": "Certification: Certified Cloud Security Professional (CCSP)" },
    { "value": "c133", "label": "Certification: Certified Information Systems Auditor (CISA)" },
    { "value": "c134", "label": "Certification: Certified in Risk and Information Systems Control (CRISC)" },
    { "value": "c135", "label": "Certification: AWS Certified Cloud Practitioner" },
    { "value": "c136", "label": "Certification: AWS Certified Developer - Associate" },
    { "value": "c137", "label": "Certification: AWS Certified SysOps Administrator - Associate" },
    { "value": "c138", "label": "Certification: AWS Certified Solutions Architect - Associate" },
    { "value": "c139", "label": "Certification: AWS Certified DevOps Engineer - Professional" },
    { "value": "c140", "label": "Certification: AWS Certified Solutions Architect - Professional" },
    { "value": "c141", "label": "Certification: AWS Certified Big Data - Specialty" },
    { "value": "c142", "label": "Certification: AWS Certified Advanced Networking - Specialty" },
    { "value": "c143", "label": "Certification: AWS Certified Security - Specialty" },
    { "value": "c144", "label": "Certification: AWS Certified Machine Learning - Specialty" },
    { "value": "c145", "label": "Certification: Google Certified Professional Cloud Architect" },
    { "value": "c146", "label": "Certification: Google Certified Professional Data Engineer" },
    { "value": "c147", "label": "Certification: Google Certified Professional Cloud Developer" },
    { "value": "c148", "label": "Certification: Google Certified Professional Cloud Network Engineer" },
    { "value": "c149", "label": "Certification: Google Certified Professional Cloud Security Engineer" },
    { "value": "c150", "label": "Certification: Google Certified Professional Cloud DevOps Engineer" }
    ]
    
export const roles =[
    {"value": "team member", "label":"Team member"},
    {"value": "team lead", "label":"Team Lead"},
    {"value": "project manager", "label":"Project manager"},
    {"value": "tester", "label":"Tester"},
    {"value": "test manager", "label":"Test manager"},
    {"value": "business analyst", "label":"Business analyst"},
    {"value": "software architect", "label":"Software Architect"},
    {"value": "software developer", "label":"Software Developer"}
]

export const provinces =[
    {"value":"gauteng", "label":"Gauteng"},
    {"value":"kwazulunatal", "label":"KwaZulu Natal"},
    {"value":"easterncape", "label":"Eastern Cape"},
    {"value":"westerncape", "label":"Western Cape"},
    {"value":"northerncape", "label":"Northern Cape"},
    {"value":"freestate", "label":"Free state"},
    {"value":"limpopo", "label":"Limpopo"},
    {"value":"northwest", "label":"North West"},
    {"value":"mpumalanga", "label":"Mpumalanga"}
]

export interface IOption{
    value:string,
    label:string
}

export function getOptionFromValue(value:string[], options:IOption[]):IOption[]{
    const res = value.flatMap(x=>{return options.filter(y=>y.value==x);})
    return res;
  }